config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'photos#index'

  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :photos do
    resources :comments, only: :create
    collection do
      get 'search'
    end
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :favorites

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  attachment :image
  has_many :comments 

  with_options presence: true do
    validates :title
    validates :body
    validates :image
  end

  def self.search(search)
    if search != ""
      Photo.where('title LIKE(?)', "%#{search}%")
    else
      Photo.all
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :photos, dependent: :destroy
  has_many :comments
  has_many :favorites

  # フォロー設定
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # フォロワー設定
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  validates :username, presence: true

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  class MyLogger < Logger
    include LoggerSilence
    include ActiveSupport::LoggerThreadSafeLevel
  end

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :mylogger_test

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :fullname])
  end

  def mylogger_test
    mylogger = MyLogger.new(STDOUT)
    mylogger.silence do
      mylogger.debug("controller = #{controller_name}")
      mylogger.info("action = #{action_name}")
      mylogger.error("controler#action = #{controller_name}##{action_name}")
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/photos/#{comment.photo.id}" # コメントと結びつく投稿された写真の詳細画面に遷移する
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, photo_id: params[:photo_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.build(photo_id: params[:photo_id])
    favorite.save
    redirect_to photos_path
  end

  def destroy
    favorite = Favorite.find_by(photo_id: params[:photo_id], user_id: current_user.id)
    favorite.destroy
    redirect_to photos_path
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.includes(:user).order("created_at DESC")
    @users = User.all
  end

  def show
    @photo = Photo.find(params[:id])
    @comment = Comment.new
    @comments = @photo.comments.includes(:user)
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user_id = current_user.id
    if @photo.save
      redirect_to photo_path(@photo)
    else
      render :new
    end
  end

  def edit
    @photo = Photo.find(params[:id])
    if @photo.user != current_user
      redirect_to root_path, alert: 'アクセスできません！'
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photo_path(@photo)
    else
      render :edit
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy
    redirect_to root_path
  end

  def search
    @photos = Photo.search(params[:keyword]).order("created_at DESC")
  end

  private
  def photo_params
    params.require(:photo).permit(:title, :body, :image)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    follow = current_user.active_relationships.build(follower_id: params[:user_id])
    follow.save
    redirect_to root_path
  end

  def destroy
    follow = current_user.active_relationships.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path, alert: 'アクセスできません！'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.followings
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.haml
%header 
  .header
    .header__contents
      .header__Photo-diary
        = icon('fas', 'camera-retro', class: "header__icon-camera")
        = link_to "Photo diary", "/", class: "header__title"
      .header__seach
        = form_with(url: search_photos_path, local: true, method: :get, class: "search-form") do |form|
          = form.text_field :keyword, placeholder: "投稿を検索", class: "search-input"
          = form.submit "検索", class: "search-btn"
      - if user_signed_in?
        %figure.current-user__icon
          = link_to user_path(current_user) do
            = attachment_image_tag current_user, :profile_image, fallback: "no-image.png", class: "current-user__image"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoDiaryApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield
    -# %footer
    -#   .footer

app/views/photos/edit.html.haml
= render partial: "layouts/header"
%body
  .photo__edit__body
    .photo__edit__form
      = form_for @photo do |f|

        .photo__edit
          .photo__edit__text
            タイトル
          = f.text_field :title, class: "edit__title"
        
        .photo__edit
          .photo__edit__text
            内容
          = f.text_area :body, class: "edit__post"
        
        .photo__edit
          .photo__edit__text
            写真
          = f.attachment_field :image, class: "edit__image"
        
        .photo__update__submit
          = f.submit '更新', class: "edit__update__btn"

-# %h1 Photos#edit
-# %p Find me in app/views/photos/edit.html.haml

app/views/photos/index.html.haml
= render partial: "layouts/header"
%body
  .header__nav
    .nav__menu
      - if user_signed_in?
        .nav__menu__text
          = link_to "フォロワー", followers_user_path(current_user.id), class: "nav__menu__btn"
        
      - if user_signed_in?
        .nav__menu__right
          .nav__menu__sign
            = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav__menu__btn"
          .nav__menu__post
            .nav__menu__post__enclosure
              = link_to "投稿", new_photo_path,  class: "post-btn"
      - else
        .nav__menu__right
          .nav__menu__sign
            = link_to "ログイン", new_user_session_path, class: "nav__menu__btn"
          .nav__menu__sign
            = link_to "新規登録", new_user_registration_path, class: "nav__menu__btn"
  .index__body
    .index__diaries__space
      .index__diaries
        - @photos.each do |photo|
          .index__diaries__contents
            .diary__user
              .diary__user__icon
                = link_to user_path(photo.user) do
                  = attachment_image_tag photo.user, :profile_image, fallback: "no-image.png", class: "diary__user__image"
              .diary__user__name
                = link_to user_path(photo.user) do
                  = photo.user.username
              - if user_signed_in?
                - if current_user != photo.user
                  - if photo.user.followed_by?(current_user)
                    .followed__btn__toppage
                      = link_to "フォロー中", user_relationships_path(photo.user.id), class: "followed__text", method: :delete
                  - else
                    .follow__btn__toppage
                      = link_to "フォローする", user_relationships_path(photo.user.id), class: "follow__text", method: :post
            = link_to photo_path(photo.id) do
              = attachment_image_tag photo, :image, class: "post__diary"
            .diary__icon__contents
              - if user_signed_in?
                -if photo.favorited_by?(current_user)
                  = link_to photo_favorites_path(photo), method: :delete do
                    .diary__heart__icon
                      = icon('fas', 'heart', class: "diary__heart")
                - else
                  = link_to photo_favorites_path(photo), method: :post do
                    .diary__heart__icon
                      = icon('far', 'heart', class: "diary__heart")
              - else
                .index__count-num
                  = photo.favorites.count
              .diary__comments__icon
                = link_to photo_path(photo.id) do
                  = icon('far', 'comment', class: "diary__comments")

    .index__users
      - if user_signed_in?
        .index__current__user
          .index__current__icon
            = link_to user_path(current_user) do
              = attachment_image_tag current_user, :profile_image, fallback: "no-image.png", class: "index-current__image"
          .index__current__username
            = link_to user_path(current_user) do
              = current_user.username
      - if user_signed_in?
        - @users.each do |user|
          - if current_user != user
            - if user.followed_by?(current_user)
              .index__reration__users
                .followed__user__icon
                  = link_to user_path(user) do
                    = attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "followed__user__image"
                .followed__user__name
                  = link_to user_path(user) do
                    = user.username
                .index__talk__icon
                  = link_to "#" do
                    = icon('far', 'comments',class: "talk__icon")

app/views/photos/new.html.haml
= render partial: "layouts/header"
%body
  .post__create__form
    = form_for @photo do |f|
      .post__form__contents
        .post__form
          .post__form__text
            タイトル
          = f.text_field :title, class: "post__input"
        
        .post__form
          .post__form__text
            内容
          = f.text_area :body, class: "post__inpiut-area"
        
        .post__form
          .post__form__text
            写真
          = f.attachment_field :image, class: "post__input-image"
        
        .post-submit__form
          = f.submit "投稿", class: "post__submit"
-# %h1 Photos#new
-# %p Find me in app/views/photos/new.html.haml

app/views/photos/search.html.haml
= render partial: "layouts/header"
%body
  .search__body
    .search-photo__contents
      - @photos.each do |photo|
        .posted-photos
          .searched-photo__title 
            = photo.title
          .searched__photo-image
            = link_to photo_path(photo.id) do
              = attachment_image_tag photo, :image, class: "searched__image"
          .searched__icon__contents
            - if user_signed_in?
              -if photo.favorited_by?(current_user)
                = link_to photo_favorites_path(photo), method: :delete do
                  .searched__heart__icon
                    = icon('fas', 'heart', class: "searched__heart")
              - else
                = link_to photo_favorites_path(photo), method: :post do
                  .searched__heart__icon
                    = icon('far', 'heart', class: "searched__heart")
            - else
              .index__count-num
                = photo.favorites.count
            .searched__comments__icon
              = link_to photo_path(photo.id) do
                = icon('far', 'comment', class: "searched__comments")
            .searched__user__icon
              = link_to user_path(photo.user) do
                = attachment_image_tag photo.user, :profile_image, fallback: "no-image.png", class: "seached__user-image"

app/views/photos/show.html.haml
= render partial: "layouts/header"
%body
  .photo__details__body
    .photo__details__contents
      .details__diary
        - if user_signed_in?
          - if @photo.user.id == current_user.id
            .details__btns
              .details__edit__btn
                = link_to "編集", edit_photo_path(@photo), class: "details-edit__text"
              .details__delete__btn
                = link_to "削除", photo_path(@photo), method: :delete, data: {confirm: "削除しますか？"}, class: "details-delete__text"
        .photo-details__title 
          = @photo.title

        .photo-details__image
          = attachment_image_tag @photo, :image, class: "details__attachment__image"
        
        .diary__texts
          .icon__contents
            - if user_signed_in?
              -if @photo.favorited_by?(current_user)
                = link_to photo_favorites_path(@photo), method: :delete do
                  .peace__icon
                    = icon('fas', 'heart', class: "heart")
              - else
                = link_to photo_favorites_path(@photo), method: :post do
                  .peace__icon
                    = icon('far', 'heart', class: "heart")
              .show__count-num
                = @photo.favorites.count
            .post-user__icon
              = link_to user_path(@photo.user) do
                = attachment_image_tag @photo.user, :profile_image, fallback: "no-image.png", class: "post-user__attachment_image"

          .photo-details__body
            = simple_format @photo.body
      
      .comment__contents
        .users__comments
          - if @comments 
            - @comments.each do |comment|
              .users__commnet__text
                .comment-user__icon
                  = link_to user_path(comment.user) do
                    = attachment_image_tag comment.user, :profile_image, fallback: "no-image.png", class: "comment-user__image"
                .commnet-user__text
                  = simple_format comment.text
        
        - if user_signed_in?
          .user-comment__submit
            = form_with(model: [@photo, @comment], local: true) do |form|
              = form.text_area :text, placeholder: "コメント", class: "comment__input"
              = form.submit "コメントする", class: "comment__btn"

app/views/relationships/_follow_btn.html.haml
-# - unless current_user == user
-#   - if current_user.following?(user)
-#     = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
-#       = f.hidden_field :follow_id, value: user.id
-#       = f.submit 'フォロー中', class: 'follow-now'
-#   - else
-#     = form_for(current_user.relationships.build) do |f|
-#       = f.hidden_field :follow_id, value: user.id
-#       = f.submit 'フォロー', class: 'follows'

app/views/users/edit.html.haml
= render partial: "layouts/header"
%body
  .profile-edit__body
    .profile-edit__form
      = form_for @user do |f|

        .edit-form__contents

          .edit-form__name
            .edit-name__text
              名前
            = f.text_field :username, class: "edit__name_email"

          .edit-form__profile
            .edit-profile__text
              プロフィール
            = f.text_area :profile, maxlength: 100, class: "edit__textarea"

          .edit-form__profile-image
            .edit-profile-image__text
              プロフィール写真
            .image__form
              = f.attachment_field :profile_image, class: "image__input"

          .edit-form__email
            .edit-email__text
              メールアドレス
            = f.email_field :email, class: "edit__name_email"

          .update-form__btn
            = f.submit "更新", class: "update__btn"


-# %h1 Users#edit
-# %p Find me in app/views/users/edit.html.haml

app/views/users/followers.html.haml
= render partial: "layouts/header"
%body
  .cuurrent-user__profile
    .mypage__nav
      = attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "mypage-user__attachment_image"
      .profil__contents
        .user-name__profil-edit
          .user__name
            = @user.username
          - if user_signed_in?
            - if @user.id == current_user.id
              .profil-edit
                = link_to "プロフィール編集", edit_user_path(current_user.id), class: "profil-edit__text"
          - if user_signed_in?
            - if current_user != @user
              - if @user.followed_by?(current_user)
                .followed__btn__mypage
                  = link_to "フォロー中", user_relationships_path(@user.id), class: "followed__text", method: :delete
              - else
                .follow__btn__mypage
                  = link_to "フォローする", user_relationships_path(@user.id), class: "follow__text", method: :post
        .post-follow__numbers
          .post-follow__numbers__nav
            投稿数
          .post-follow__numbers__nav
            = link_to "フォロー", follows_user_path(@user.id)
          .post-follow__numbers__nav
            = link_to "フォロワー", followers_user_path(@user.id)
        .profil__text
          = simple_format @user.profile

  .follows__main
    .follows__users__contents
      - @users.each do |user|
        .follows__list
          .follows__content
            .follows__icon
              = link_to user_path(user) do
                = attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "follows__icon__image"
            .follows__name
              = link_to user_path(user) do
                = user.username
            - if current_user != user
              - if user.followed_by?(current_user)
                .follows__text
                  = link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "follows__text__font"
              - else
                .followers__text
                  = link_to "フォロー", user_relationships_path(user.id), method: :post, class: "followers__text__font"

app/views/users/follows.html.haml
= render partial: "layouts/header"
%body
  .cuurrent-user__profile
    .mypage__nav
      = attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "mypage-user__attachment_image"
      .profil__contents
        .user-name__profil-edit
          .user__name
            = @user.username
          - if user_signed_in?
            - if @user.id == current_user.id
              .profil-edit
                = link_to "プロフィール編集", edit_user_path(current_user.id), class: "profil-edit__text"
          - if user_signed_in?
            - if current_user != @user
              - if @user.followed_by?(current_user)
                .followed__btn__mypage
                  = link_to "フォロー中", user_relationships_path(@user.id), class: "followed__text", method: :delete
              - else
                .follow__btn__mypage
                  = link_to "フォローする", user_relationships_path(@user.id), class: "follow__text", method: :post
        .post-follow__numbers
          .post-follow__numbers__nav
            投稿数
          .post-follow__numbers__nav
            = link_to "フォロー", follows_user_path(@user.id)
          .post-follow__numbers__nav
            = link_to "フォロワー", followers_user_path(@user.id)
        .profil__text
          = simple_format @user.profile

  .follows__main
    .follows__users__contents
      - @users.each do |user|
        .follows__list
          .follows__content
            .follows__icon
              = link_to user_path(user) do
                = attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "follows__icon__image"
            .follows__name
              = link_to user_path(user) do
                = user.username
            - if current_user != user
              - if user.followed_by?(current_user)
                .follows__text
                  = link_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "follows__text__font"

app/views/users/index.html.haml
= render partial: "layouts/header"
%body
  .cuurrent-user__profile
    .mypage__nav
      = attachment_image_tag current_user, :profile_image, fallback: "no-image.png", class: "mypage-user__attachment_image"
      .profil__contents
        .user-name__profil-edit
          .user__name
            = current_user.username
          - if current_user.id
            .profil-edit
              = link_to "プロフィール編集", edit_user_path(current_user.id), class: "profil-edit__text"
        .post-follow__numbers
          .post-follow__numbers__nav
            投稿数
          .post-follow__numbers__nav
            フォロー中  人
          .post-follow__numbers__nav
            フォロワー  人
        .profil__text
          = simple_format current_user.profile
  -# %h1 Users#index 
  -# %p Find me in app/views/users/index.html.haml

  .users__main
    .users__contents
      - @users.each do |user|
        %figure.user__profile__image
          = link_to user_path(user) do
            .user__image__name
              = attachment_image_tag user, :profile_image, fallback: "no-image.png", class: "attachment_image"
              .users__name
                = user.username
              .follow__text
                -# = link_to "フォロー中", "#", class: "under__follow"

app/views/users/show.html.haml
= render partial: "layouts/header"
%body
  .cuurrent-user__profile
    .mypage__nav
      = attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "mypage-user__attachment_image"
      .profil__contents
        .user-name__profil-edit
          .user__name
            = @user.username
          - if user_signed_in?
            - if @user.id == current_user.id
              .profil-edit
                = link_to "プロフィール編集", edit_user_path(@user), class: "profil-edit__text"
          - if user_signed_in?
            - if current_user != @user
              - if @user.followed_by?(current_user)
                .followed__btn__mypage
                  = link_to "フォロー中", user_relationships_path(@user.id), class: "followed__text", method: :delete
              - else
                .follow__btn__mypage
                  = link_to "フォローする", user_relationships_path(@user.id), class: "follow__text", method: :post

        .post-follow__numbers
          .post__numbers__text
            投稿数 :
          .post__numbers
            = @user.photos.count
          .post-follow__numbers__nav
            = link_to "フォロー", follows_user_path(@user.id)
          .post-follow__numbers__nav
            = link_to "フォロワー", followers_user_path(@user.id)
        .profil__text
          = simple_format @user.profile
  .user__profile__body
    .user__posted__images
      - @user.photos.each do |photo|
        = link_to photo_path(photo) do
          = attachment_image_tag photo, :image, fallback: "no-image.png", class: "posted__image"